### PR TITLE
Character Controller and other things

### PR DESCRIPTION
**Pull request by VegeoStudios**
- Created input handler to work with new unity input system
- Set render pipeline to URP
- Added character controller package
- Added demo 2D character controller to scene
- Created input handler to work with new unity input system
- Organized gameobjects in scene
- Changed prototype map to test character controller
- Anchored camera to character

### CODE REVIEW

**Comment by BrendenDomingo** [comment]
Rebase

**Review by BrendenDomingo — CHANGES_REQUESTED** [review]
Remove User Settings

**Review by BrendenDomingo — CHANGES_REQUESTED** [review]
Remove Documentation

**Review by BrendenDomingo — CHANGES_REQUESTED** [review]
Do we need everything in the presets folder? At least remove the readmes

**Review by BrendenDomingo — CHANGES_REQUESTED** [review]
Looks like we can remove resources, and icons

**Review by BrendenDomingo — CHANGES_REQUESTED** [review]
Do we need the materials

**Review by BrendenDomingo — CHANGES_REQUESTED** [review]
Can we remove the Imgs folder

**Review by BrendenDomingo — DISMISSED** [review]

**Review by Kharjai — CHANGES_REQUESTED** [review]
This seems extremely overkill for what we're starting out with. A lot of these classes def look useful but this is a gigantic PR with a load of files that we may never use. Imo, let's instead pull things in and/or adapt code as we need it rather than just dump an entire package into the repo.

**Pull request closed without merging**
